export const LOGIN_AS_EMPLOYEE_REQUEST = "LOGIN_AS_EMPLOYEE_REQUEST"
export const LOGIN_AS_EMPLOYEE_SUCCESS = "LOGIN_AS_EMPLOYEE_SUCCESS"
export const LOGIN_AS_EMPLOYEE_FAIL = "LOGIN_AS_EMPLOYEE_FAIL"
export const LOGIN_AS_EMPLOYEE_RESET = "LOGIN_AS_EMPLOYEE_RESET"

export const REGISTER_AS_EMPLOYEE_REQUEST = "REGISTER_AS_EMPLOYEE_REQUEST"
export const REGISTER_AS_EMPLOYEE_SUCCESS = "REGISTER_AS_EMPLOYEE_SUCCESS"
export const REGISTER_AS_EMPLOYEE_FAIL = "REGISTER_AS_EMPLOYEE_FAIL"
export const REGISTER_AS_EMPLOYEE_RESET = "REGISTER_AS_EMPLOYEE_RESET"
