export const LOGIN_AS_EMPLOYEE_REQUEST = "LOGIN_AS_EMPLOYEE_REQUEST"
export const LOGIN_AS_EMPLOYEE_SUCCESS = "LOGIN_AS_EMPLOYEE_SUCCESS"
export const LOGIN_AS_EMPLOYEE_FAIL = "LOGIN_AS_EMPLOYEE_FAIL"
export const LOGIN_AS_EMPLOYEE_RESET = "LOGIN_AS_EMPLOYEE_RESET"

export const REGISTER_AS_EMPLOYEE_REQUEST = "REGISTER_AS_EMPLOYEE_REQUEST"
export const REGISTER_AS_EMPLOYEE_SUCCESS = "REGISTER_AS_EMPLOYEE_SUCCESS"
export const REGISTER_AS_EMPLOYEE_FAIL = "REGISTER_AS_EMPLOYEE_FAIL"
export const REGISTER_AS_EMPLOYEE_RESET = "REGISTER_AS_EMPLOYEE_RESET"

export const LOGIN_AS_ADMIN_REQUEST = "LOGIN_AS_ADMIN_REQUEST"
export const LOGIN_AS_ADMIN_SUCCESS = "LOGIN_AS_ADMIN_SUCCESS"
export const LOGIN_AS_ADMIN_FAIL = "LOGIN_AS_ADMIN_FAIL"
export const LOGIN_AS_ADMIN_RESET = "LOGIN_AS_ADMIN_RESET"

export const REGISTER_COMPLAINT_REQUEST = "REGISTER_COMPLAINT_REQUEST"
export const REGISTER_COMPLAINT_SUCCESS = "REGISTER_COMPLAINT_SUCCESS"
export const REGISTER_COMPLAINT_FAIL = "REGISTER_COMPLAINT_FAIL"
export const REGISTER_COMPLAINT_RESET = "REGISTER_COMPLAINT_RESET"

export const GET_ALL_MY_COMPLAINT_REQUEST = "GET_ALL_MY_COMPLAINT_REQUEST"
export const GET_ALL_MY_COMPLAINT_SUCCESS = "GET_ALL_MY_COMPLAINT_SUCCESS"
export const GET_ALL_MY_COMPLAINT_FAIL = "GET_ALL_MY_COMPLAINT_FAIL"
export const GET_ALL_MY_COMPLAINT_RESET = "GET_ALL_MY_COMPLAINT_RESET"

export const GET_ALL_EMPLOYEE_COMPLAINT_REQUEST = "GET_ALL_EMPLOYEE_COMPLAINT_REQUEST"
export const GET_ALL_EMPLOYEE_COMPLAINT_SUCCESS = "GET_ALL_EMPLOYEE_COMPLAINT_SUCCESS"
export const GET_ALL_EMPLOYEE_COMPLAINT_FAIL = "GET_ALL_EMPLOYEE_COMPLAINT_FAIL"
export const GET_ALL_EMPLOYEE_COMPLAINT_RESET = "GET_ALL_EMPLOYEE_COMPLAINT_RESET"

export const GET_WORKERS_LIST_REQUEST = "GET_WORKERS_LIST_REQUEST"
export const GET_WORKERS_LIST_SUCCESS = "GET_WORKERS_LIST_SUCCESS"
export const GET_WORKERS_LIST_FAIL = "GET_WORKERS_LIST_FAIL"
export const GET_WORKERS_LIST_RESET = "GET_WORKERS_LIST_RESET"

export const ASSIGN_COMPLAINT_TO_WORKERS_REQUEST = "ASSIGN_COMPLAINT_TO_WORKERS_REQUEST"
export const ASSIGN_COMPLAINT_TO_WORKERS_SUCCESS = "ASSIGN_COMPLAINT_TO_WORKERS_SUCCESS"
export const ASSIGN_COMPLAINT_TO_WORKERS_FAIL = "ASSIGN_COMPLAINT_TO_WORKERS_FAIL"
export const ASSIGN_COMPLAINT_TO_WORKERS_RESET = "ASSIGN_COMPLAINT_TO_WORKERS_RESET"